name: The Power of Storytelling
markdown: kramdown
pygments: false
baseurl: /storytelling/2013/
destination: public
exclude:
  - Minafile
  - wercker.yml
  - Gemfile
  - Gemfile.lock
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
assets:
  js_compressor: uglifier
  css_compressor: sass
  baseurl: /storytelling/2013/assets/
  cachebust: soft
