name: The Power of Storytelling
markdown: kramdown
highlighter: null
baseurl: /storytelling/2013/
destination: public
permalink: /blog/:title
exclude:
  - Minafile
  - wercker.yml
  - Gemfile
  - Gemfile.lock
assets:
  #js_compressor: uglifier
  # css_compressor: sass
  baseurl: /storytelling/2013/assets/
  cachebust: soft
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false